apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: afmw34o3k-java-springboot
  janus-idp.io/tekton: afmw34o3k-java-springboot
  backstage.io/kubernetes-id: afmw34o3k-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: afmw34o3k-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
